---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure components (storage, networking, monitoring)

  sourceRepos:
    - '*'

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  # Allow cluster-level resources needed for infrastructure
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  # Roles for infrastructure project
  roles:
    - name: infrastructure-admin
      description: Admin privileges for infrastructure applications
      policies:
        - p, proj:infrastructure:infrastructure-admin, applications, *, infrastructure/*, allow
      groups:
        - infrastructure-admins
