---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: postgres-operator
  namespace: argocd
spec:
  description: Project for the CrunchyData Postgres Operator
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'