apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-2"  # Deploy after PostgreSQL and external-secrets, before Authentik
spec:
  project: default
  source:
    repoURL: git@github.com:storsteinbono/gitops.git
    targetRevision: HEAD
    path: infrastructure/netbird/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: netbird
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/audit: baseline
        pod-security.kubernetes.io/warn: baseline
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
