apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1
  storage:
    size: 10Gi

  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: immich-user
      
      - name: test-user
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: test-user

    backup:
      barmanObjectStore:
        destinationPath: /backup/postgres
        wal:
          compression: gzip
      volumes:
        - name: nfs-backup
          csi:
            driver: smb.csi.k8s.io
            volumeAttributes:
              source: "//172.16.16.91/Backups"
