apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1
  storage:
    size: 10Gi

  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: immich-user
      - name: mediamanager
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: mediamanager-user
      - name: pg_prowlarr
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: prowlarr-user
      - name: pg_radarr
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: radarr-user
      - name: pg_sonarr
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: sonarr-user
        
