---
# Temporary pod to test database connection
# Delete after testing: kubectl delete pod -n postgres test-db-connection
apiVersion: v1
kind: Pod
metadata:
  name: test-db-connection
  namespace: postgres
spec:
  restartPolicy: Never
  containers:
    - name: psql
      image: postgres:16
      command:
        - sleep
        - "3600"
      env:
        # Test with the external secret credentials
        - name: PGHOST
          value: "postgresql-rw"
        - name: PGPORT
          value: "5432"
        - name: PGDATABASE
          value: "mediamanager"
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: mediamanager-user
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: mediamanager-user
              key: password
