---
# This SealedSecret will be automatically deployed with the app!
# The Sealed Secrets controller will decrypt it into a regular Secret
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: example-app-secrets
  namespace: example-app
spec:
  encryptedData:
    # These are EXAMPLE encrypted values - replace with real ones!
    # To generate:
    # 1. Create a regular secret file:
    #    cat > secret.yaml <<EOF
    #    apiVersion: v1
    #    kind: Secret
    #    metadata:
    #      name: example-app-secrets
    #      namespace: example-app
    #    stringData:
    #      database-url: "postgresql://user:pass@db:5432/mydb"
    #      api-key: "sk-1234567890abcdef"
    #      admin-password: "changeme123"
    #    EOF
    #
    # 2. Encrypt it:
    #    kubeseal --format=yaml < secret.yaml > sealedsecret.yaml
    #
    # 3. Replace this file with the output
    #
    database-url: AgBQ7Vn8kF2xKz9...REPLACE_WITH_REAL_ENCRYPTED_VALUE...
    api-key: AgCT9Kx2mE5pLw...REPLACE_WITH_REAL_ENCRYPTED_VALUE...
    admin-password: AgDX4Zp1wR3qM...REPLACE_WITH_REAL_ENCRYPTED_VALUE...
  template:
    metadata:
      name: example-app-secrets
      namespace: example-app
    type: Opaque
