---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-backup-smb
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgAkzw2ASkI35fChlBATBXE2m5kBx7Ke0TgIUvGr6qKJnG+oCT6qQA3eIijodz/GOecxni/AxDoQVcKvnBRAfla5hvIgrStG6FB78DrsZNKUUmtpZqGD6QtjU1LmRXP94He9r/gtYr6M8J3tp28uMcaDF6CFx5BCO5vHr3PuoJNBZGE+UNpPWjJF+9gyZot/EMOlRZyCQTyytzpcrL6ENVjqWZCMfGzFwDRbK6NvBMhi1601aLgXOU+sbRchg7ULjSYeXHs0rQV4cAmSEmg3ttGt10xazNrW7ZKGTPi6sQjKM1oszfwoAWkrJwuo4bfCH9ym++2Du3d3RCwLMo+GAYyi6mciXH9MwEnvKzZRG4RFgQ+mosGttEQfQtc1QIaPRBHyqGYkx6JLmbHXNbd5P1bf5LOdIR9g8AUPQArT3SXuX9H0fz9Gw91t3LldT+ongdTS4LXP0nbnxscZFyP3LL7SD6SCt9odga9Cs3lZLvNLCEBfLtoVxQL4dJmrDNArLZg2ciTvWOTtI3UqE105klAOnxHLJLnq6inwe1atUMFNB2KnYqurraek5TsFeWf33ls/Trj6FwBC44LiNnQN4jwYpKLyOq4B9paIJOwyrKk5C0alxYzuRGcOzgTsMIndeYUQxV95VNbYdo685aqYia2E0ObiujfnO2ilmC7+UsuboG77/Us8Td/mPOAAM+LYF8qAwxvGb3ENvtcWFsBLkmDEZulTAA==
    CIFS_USERNAME: AgASWVMKiVw9lIH1G7iYHpNZ9z6xP+inpvOW36pHwbgL0tGOQmtXy8pgn/SPz113PPyXa7Z6BUKjkvQWVk5OtoIwNW3VvRryKRH1idxkeSePu6FoQMDH2disOr3g08iFamJeFm2xjoYcBfqmFH1gi+P4wfcKmZH5eHejrFRJqipoIF5SAmrEGTA2JutfgnyTp7mP1PW72RMElCOstRg9mnD3tb3VQpMW45ClDHbnR09gf4+kgkVLlCCl7In66N+7RiVwgVFOJcRYJRFXfTR1bTRLk5KJ+8p0nPusKptAl/fRKgI+yvd6lHxFW2P7gYp9PwfMRIfbnDzY4Bwi94igkcKIOedQDJCwmHNbcjR9IPoM/DLjQCzVrWSt3f8LjjGnAac3c0v8jLiC6F+bWwucacAH+mJTwW5+30FxsV0OE7cAMW0jPata2/0tx4zHwcdWsvdiRGL9wof8fdrK3ZwT/3cgocXI6tsn4SD5iQHTIE2rOerZXnYMdei+Cqk4mYW08+ndx1m01r5ISMP6FzOAK0V7a3K+V43OUIMhExzshahQnkOtqqtxq/DwY/LlJpNUvcTUrQ9zQb6XZ9XePz/nmJOKyk80h7ST0rEUZnHEU6bUCXPqXYdPPszG19nNfw9WR9W5Fe6fuK8ylUus+wNnWM7m7YLMYleOLsQrnAhiLSqWzfLJ9FXgpa14py6F5AhQtRbay3yMAsxI8AAO2JA=
  template:
    metadata:
      name: longhorn-backup-smb
      namespace: longhorn-system
    type: Opaque
