---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-backup-smb
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgBnDj0Vqkfc6Fn6wuEcX3hwDIbmypyog3HETrzq5xgXkIofWdkAi7Qi8eSN9z4UWOcAcTlqxjVIhCRAKR+6eQE5AlwRSfRyTp0/HOB1ZNC5vQhST1hgcoeBlgsldx/N98dYYpC4R0uChH1NxhYaqgPQusjg72cjnLNAYyUrD14bkLlmHWNSOYI84N8+rfqlWuoHWxHXrKfbfWejt8L7wxj1xgJ18cIv1lIeJdpYCCww26zQptKgklXpRjx/LVfgS24u97W7duVx1bG4MDqkzFF+DDYeSC2NgWazZkZlTh0CkL8QtqApiQ3L88IgMMXoH0nqUgiBPOqZqwOjGrq/KfB8L6/Ynuo11PkLjTojobVBem+Vz00H08y6y9uCb7GzYXhvR6cVlBtbxH9H6gyyi9J9tMvPo7Ktu6Qy8fjdW8R5AfomAekuEGUH6ETx2kNzzljRrlnVwmtWIgxZvkRMtLXvxy2lgt1PBX2XjCKAxtuxYtOMEF6mkIfSRIBKJIyzv5QyuQG7ND5OL5FbXKck/aAZ5iVWXmvlRbXuMtkph0K1Cml1BcBLbFT6lioF8PAh16c1+S2lAoqAxF4bUPC/Mi4zWiuHIw4xddF63D1SDdV0s7W3JUWgyauHyLUuWICrFgOgexLleZubkBrTc94rDpC9np+tJfSETAHpoPxfRwsslNvYGWh2IgiCb1AqljMnlEJI68UR41KpWukLjwMXyw==
    CIFS_USERNAME: AgBcLGAPEj2fFIIujy2w08t4IR+u+7/UE+UpwbGuCBlbz8WGvRrH0nUMM3uyU3HLxTkcRRMCxs+mEfKQSkvU4VcistQq6L29QQkhv+j3ZANKwQkp/ghaCoCFi59HD8uk21btDCYn8PvghFQCIy5fEJHm70o8TssdbmVdG9b9MhuIQzjjJJ5VmfCYXu1MggAkyB9GLbjX1hsQ8E6as6/yq6LIFKOI+kl2WjXQU5z056LvB90qz0xMxeqGDFKSnHBDMNC9W2H6lzeKt22H9P/oovFk4kksHgXj/a9EyyHjxu4rJXCuMSM9TZ90CcZfE1s5YJGNpXL1gMsjzk/ByTS9sGYtGXZbA6y95TWZdWwULGQw4DALcOMOstQX7LI3dB4DbFHuuEm3UVHsJX90NNqOhnuZQdrD0yXhKWd+oIN4KbXW/MC4GPFhIvY2WbmDIiCcVD6v3ngC04jxNk3KLyteqHuCp+6CSL0lzmfEioBkCtr7aI6wMjnTC/TijuputEQUes023fDLnTWm4AAu/Nx4yN7YybhXsmCZv7OLNa8Vhyv1yDFBmizPVICPXrbj0oiUk+GwTHJOJz/QnCKis7droWcmr7mkaI5ym900cM66L0IE/UTneIN1Rr8/7fopIjzF3rSgsM2GaWF85JpvbudSWOUo/NtgLlHs6FWiJJfu6WMcGzNmLolP3WnLCVk1iUAhzCliPyJTv73Wzw==
  template:
    metadata:
      name: longhorn-backup-smb
      namespace: longhorn-system
    type: Opaque
