---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.10.1
    helm:
      releaseName: longhorn
      values: |
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 3
          reclaimPolicy: Retain

        defaultSettings:
          backupTargetURL: "cifs://172.16.16.91/Backupstest"
          credentialSecret: "longhorn-backup-smb"
          defaultReplicaCount: 3
          defaultDataLocality: disabled
          replicaSoftAntiAffinity: false
          replicaAutoBalance: disabled
          storageOverProvisioningPercentage: 200
          storageMinimalAvailablePercentage: 25
          upgradeChecker: true
          defaultLonghornStaticStorageClass: longhorn-static
          nodeDownPodDeletionPolicy: do-nothing
          allowNodeDrainWithLastHealthyReplica: false
          mkfsExt4Parameters: ""
          guaranteedInstanceManagerCpu: 12
          priorityClass: ""
          autoSalvage: true
          autoDeletePodWhenVolumeDetachedUnexpectedly: true
          disableSchedulingOnCordonedNode: true
          replicaZoneSoftAntiAffinity: true
          volumeAttachmentRecoveryPolicy: wait
          nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
          allowVolumeCreationWithDegradedAvailability: true
          autoCleanupSystemGeneratedSnapshot: true
          concurrentAutomaticEngineUpgradePerNodeLimit: 0
          backingImageCleanupWaitInterval: 60
          guaranteedEngineManagerCpu: 12
          guaranteedReplicaManagerCpu: 12

        ingress:
          enabled: false

        service:
          ui:
            type: ClusterIP

        # Talos-specific configuration
        longhornManager:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule

        longhornDriver:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule

        # Disable pre-upgrade checker (not compatible with Talos)
        preUpgradeChecker:
          jobEnabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
