---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: postgres-daily-backup
  namespace: longhorn-system
spec:
  cron: "0 2 * * *"
  task: "backup"
  groups:
  - postgresql
  retain: 7
  concurrency: 2
  labels:
    app: postgresql