---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-backup-smb
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgBn65hgJbftTH61JnZtkha7DDhx9Qh/YtDgSvewaiE7J72z5Y+GYgggP8cjZX0MNojrLiLQ1ou/q4IE9HCluF9tUVrUoZT1Vn7Tb134QhD+m6sWss/lChg1GMvoIAgBg4RV3FzOor7VT5rbaYBqpV0Z1b0V+rOYh0U2lzO20Bcm8RgHQeaSnm9K+VKvNYHFJflwzSO/2EBUpPAp0XzuyrbxB/4QOs1TqqiJdCHEyfJCGWfI/aKFks+Z518lKN+Ozkv9wQ3xVoxZ2Bs2F1riNjCO9EjXUlA3IvDtuF+s7m6ixGO5fAONDhjcLVePCil3bbdM+M34jMrnY2XyQ6m1Q4h/KOaBUQxqDCpQwdRWvPez4itbf2qVJ2zH9zY257Ce3dq7ANyO05CV46ipY3aUd/Mf1Z/yEwF7HQapICf5XDjlp9LlPd4a5PoF1kNcaVxAvwKXF0VToB2lZn8JtFqst6gY5vCoCdJu8rjzuBmU3DFzKDkQEGjd6/hw/7hdHY6lVGZgrhP8gszUAJb0DGr4UAlNyuY+uiFUA37/05MHbqaZnmIQvD2W0qgHXTsoTrMNHVnMXwAf/aFZ8EwmMS36y+h3p4snzrrgYXzBrXFI5U2NdB8YBoco0dE+J9jgvEBsklOzRGExnKA/MuodlJGLKkGMJYWeeyNzm+mcpeiN3bXv8a4ogknQFN7nfjXCFmca1avB7Nx7mMwqpDmc5Ddnsw==
    CIFS_USERNAME: AgCVW/Q5HRhCDiQuxYnS/zYvAlP++4cxIYwtor6C5KooAM5nkyabvll3tXfzbAaQk0bSHfdVnqqq9+t9YizXOZczdwOJw8RSFx1Um3or7Inaz6xdLySd4JF0Be2l3lw6xCDyx2G7bPusXvWmey7kXWgpPS9BGYHI83ktbqXMns7a7hIBTQl/p7wyd4o5JGvi0QaDyEbqwNYF7Mrw+0yVDMhliItIAm3iGKJkphxtMsxmqRnbb2gOIazVWr8lV+Ko7bblGj8K5PPtX9kJruJdC7gA2e3w4urDhdO34xyMHsma5dF/S6w+iBhsFFamixTZKg5PEW2I8BRKVxnUZUVxK4opU6a0uV9Zu4XNYgXQwzB/NNjg84W7p0+16lR68OmwmKS8XXii2oNiDMI86oOIaosXK7Lhb6qO0J/xtdbuU1QWJYmTwLjC55oMiG37jUcnuQIvcGUJQrEyy0Snyymt1lXmxeWtPPPoVxooVFIXmWq7zMspa4Hg8KOI0NLqKpCb5NGhqU5+u0M4ysdYpU/4LVlG7T9JNfm2Qbkjl5LoXIgwqG45hWK/v6edaAgFbYlHhvZ8S6eEmlcyh+pp+xrn98fRztEB+Wsefd2YC+vgCuvhPYejdJ1kkWUaFWkOLmemXkWub0aK3WZ3BVRMn8igZ5ZJlV37o7Dbpy96CMQ4Nj5iCGsMpskq9QUb073vTCgdzjnk9Yh5c1cgJA==
  template:
    metadata:
      name: longhorn-backup-smb
      namespace: longhorn-system
    type: Opaque
