---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-smb
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: longhorn-backup-smb
    creationPolicy: Owner
  data:
    - secretKey: CIFS_USERNAME
      remoteRef:
        key: longhorn-smb-username
    - secretKey: CIFS_PASSWORD
      remoteRef:
        key: longhorn-smb-password
