apiVersion: v1
kind: Secret
metadata:
  name: immich-user
  namespace: postgres
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: immich
  password: smallHous389
