apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-user
  namespace: postgres
spec:
  managed:
    roles:
    - name: immich
      ensure: present
      login: true
      passwordSecret:
        name: immich-user
