  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: metrics-server
    namespace: argocd
    annotations:
      argocd.argoproj.io/sync-wave: "-1"  # Deploy with other utilities
    finalizers:
      - resources-finalizer.argocd.argoproj.io
  spec:
    project: default
    source:
      chart: metrics-server
      repoURL: https://kubernetes-sigs.github.io/metrics-server/
      targetRevision: 3.12.2
      helm:
        releaseName: metrics-server
        values: |
          args:
            - --kubelet-insecure-tls
    destination:
      server: https://kubernetes.default.svc
      namespace: kube-system
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
