apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"  # Install before operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/external-secrets/external-secrets.git
    targetRevision: v0.10.6  # Match a stable version
    path: deploy/crds
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false  # Don't prune CRDs automatically
      selfHeal: true
    syncOptions:
      - Replace=true  # Replace existing CRDs
