apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 1.2.1
      helm:
        releaseName: external-secrets
        values: |
          installCRDs: true
          replicaCount: 1
          serviceAccount:
            create: true
            name: external-secrets
    - repoURL: git@github.com:storsteinbono/gitops.git
      targetRevision: HEAD
      path: infrastructure/external-secrets/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
