apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
  namespace: postgres
spec:
  name: immich
  owner: immich
  cluster:
    name: postgresql
  extensions:
    - name: vchord
      ensure: present
    - name: earthdistance
      ensure: present