apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-db
  namespace: postgres
spec:
  cluster:
    name: postgresql
  name: immich
  owner: immich  # This role is now managed in cluster.spec.managed.roles
