apiVersion: batch/v1
kind: Job
metadata:
  name: immich-db-setup
  namespace: postgres
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: setup
          image: ghcr.io/cloudnative-pg/postgresql:18.1
          env:
            - name: PGHOST
              value: postgresql-rw
            - name: PGDATABASE
              value: postgres
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: password
            - name: IMMICH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-immich
                  key: password
          command:
            - /bin/bash
            - -c
            - |
              set -e
              until pg_isready; do sleep 2; done

              echo "Setting password for immich role..."
              psql -c "ALTER ROLE immich WITH PASSWORD '${IMMICH_PASSWORD}';"

              echo "Granting database permissions..."
              psql -c "GRANT ALL PRIVILEGES ON DATABASE immich TO immich;"

              echo "✓ Immich database setup complete"
