  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: reloader
    namespace: argocd
    annotations:
      argocd.argoproj.io/sync-wave: "-1"  # Deploy with other utilities
    finalizers:
      - resources-finalizer.argocd.argoproj.io
  spec:
    project: default
    source:
      chart: reloader
      repoURL: https://stakater.github.io/stakater-charts
      targetRevision: 1.2.1
      helm:
        releaseName: reloader
    destination:
      server: https://kubernetes.default.svc
      namespace: reloader
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true