---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-immich-pv
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  nfs:
    server: 172.16.16.91
    path: /volume/f72a1a74-f3ab-46af-8bd9-d97aaa05e733/.srv/.unifi-drive/immich/.data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  resources:
    requests:
      storage: 1Ti
  volumeName: nfs-immich-pv
