apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: postgresql
spec:
  instances: 3 # High availability with 3 replicas

  # PostgreSQL 17 - latest stable version
  imageName: ghcr.io/cloudnative-pg/postgresql:17-minimal-trixie

  # Superuser credentials
  superuserSecret:
    name: postgres-superuser

  # Bootstrap - only used during initial cluster creation
  bootstrap:
    initdb:
      database: postgres
      owner: postgres
      secret:
        name: postgres-superuser

  # Storage configuration - uses Longhorn
  storage:
    storageClass: longhorn
    size: 50Gi # Adjust based on your needs

  # Resource requests and limits
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

  # PostgreSQL configuration parameters
  postgresql:
    parameters:
      # From your Ansible config
      listen_addresses: "0.0.0.0" # In Kubernetes, listen on all interfaces
      logging_collector: "off"

      # Additional recommended parameters for production
      max_connections: "200"
      shared_buffers: "1GB"
      effective_cache_size: "3GB"
      maintenance_work_mem: "256MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "5242kB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      max_worker_processes: "4"
      max_parallel_workers_per_gather: "2"
      max_parallel_workers: "4"
      max_parallel_maintenance_workers: "2"

    # pg_hba.conf rules - HOST BASED AUTHENTICATION
    # Converted from your Ansible postgresql_hba_entries
    pg_hba:
      # CloudNativePG creates these fixed rules automatically:
      # - local all all peer
      # - hostssl postgres streaming_replica all cert
      # - hostssl replication streaming_replica all cert

      # Allow connections from Kubernetes pod network (adjust to match your CNI)
      # This replaces "samenet" from Ansible config
      - host semaphore_ui terraform 10.0.0.0/8 scram-sha-256
      - host semaphore_ui terraform 172.16.0.0/12 scram-sha-256
      - host semaphore_ui terraform 192.168.0.0/16 scram-sha-256

      - host immich terraform 10.0.0.0/8 scram-sha-256
      - host immich terraform 172.16.0.0/12 scram-sha-256
      - host immich terraform 192.168.0.0/16 scram-sha-256

      - host teslamate terraform 10.0.0.0/8 scram-sha-256
      - host teslamate terraform 172.16.0.0/12 scram-sha-256
      - host teslamate terraform 192.168.0.0/16 scram-sha-256

      - host teslamate teslamate 10.0.0.0/8 scram-sha-256
      - host teslamate teslamate 172.16.0.0/12 scram-sha-256
      - host teslamate teslamate 192.168.0.0/16 scram-sha-256

      # Allow all users to postgres database (for administrative tasks)
      - host postgres all 10.0.0.0/8 scram-sha-256
      - host postgres all 172.16.0.0/12 scram-sha-256
      - host postgres all 192.168.0.0/16 scram-sha-256

      # Optional: Allow pgAdmin to connect to all databases
      - hostssl all all 10.0.0.0/8 scram-sha-256
      - hostssl all all 172.16.0.0/12 scram-sha-256
      - hostssl all all 192.168.0.0/16 scram-sha-256

  # Monitoring (optional - enable if you have Prometheus)
  monitoring:
    enablePodMonitor: false

  # Backup configuration (recommended for production)
  # Uncomment and configure if you have S3/MinIO
  # backup:
  #   retentionPolicy: "30d"
  #   barmanObjectStore:
  #     destinationPath: s3://your-bucket/postgres-backups
  #     s3Credentials:
  #       accessKeyId:
  #         name: s3-credentials
  #         key: ACCESS_KEY_ID
  #       secretAccessKey:
  #         name: s3-credentials
  #         key: ACCESS_SECRET_KEY
  #     wal:
  #       compression: gzip
  #     data:
  #       compression: gzip
