apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebrowser
  namespace: filebrowser
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:storsteinbono/gitops.git
    targetRevision: HEAD
    path: manifests/filebrowser
  destination:
    server: https://kubernetes.default.svc
    namespace: filebrowser
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
