# Example Regular Kubernetes Secret (DO NOT COMMIT THIS TO GIT!)
# This is just for reference - you'll encrypt this into a SealedSecret
---
apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
  namespace: default
type: Opaque
stringData:
  database-url: "postgresql://user:password@postgres:5432/mydb"
  api-key: "super-secret-api-key"
  username: "admin"
  password: "changeme123"
