---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-8"  # After Cilium LB config (-9), before Traefik (-5)
spec:
  project: default
  source:
    repoURL: git@github.com:storsteinbono/gitops.git
    targetRevision: HEAD
    path: infrastructure/coredns/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
