apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: postgres
spec:
  instances: 3

  # Specify version to avoid auto-upgrade issues
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2

  storage:
    size: 10Gi
