---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-user
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: immich-user
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: postgres-immich-username
    - secretKey: password
      remoteRef:
        key: postgres-immich-password
