---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mediamanager-credentials
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: mediamanager-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: mediamanager-user
    - secretKey: password
      remoteRef:
        key: mediamanager-password
    - secretKey: db_hostname
      remoteRef:
        key: mediamanager-db-hostname
    - secretKey: db_port
      remoteRef:
        key: mediamanager-db-port
    - secretKey: db_name
      remoteRef:
        key: mediamanager-db-name
