apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"  # Install before operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/cloudnative-pg/cloudnative-pg.git
    targetRevision: v1.24.1
    path: config/crd/bases
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
