apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/storsteinbono/gitops.git
    targetRevision: HEAD
    path: apps/postgresql/base

  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Ignore differences in sync policy for manual debugging
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jsonPointers:
        - /spec/syncPolicy
