---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Install before other apps
spec:
  project: infrastructure
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.16.2
    helm:
      releaseName: sealed-secrets-controller
      values: |
        # Sealed Secrets Controller Configuration
        fullnameOverride: sealed-secrets-controller

        # Controller configuration
        controller:
          # Create the controller deployment
          create: true

        # Install CRDs
        crds:
          create: true
          keep: true  # Keep CRDs on uninstall

        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          fsGroup: 65534

        # Pod security context
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1001
          fsGroup: 65534

        # Resources
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi

        # Service account
        serviceAccount:
          create: true
          name: sealed-secrets-controller

        # RBAC
        rbac:
          create: true
          pspEnabled: false

        # Metrics
        metrics:
          serviceMonitor:
            enabled: false  # Enable if you have Prometheus Operator
          dashboards:
            create: false

        # Command line flags for the controller
        commandArgs:
          - "--update-status"
          - "--key-renew-period=720h"  # 30 days

        # Ingress (disabled by default)
        ingress:
          enabled: false

        # Priority class
        priorityClassName: ""

        # Node selector
        nodeSelector: {}

        # Tolerations
        tolerations: []

        # Affinity
        affinity: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system  # Install in kube-system for kubeseal CLI compatibility

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false  # kube-system already exists
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health assessment
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
