apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bentopdf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:storsteinbono/gitops.git
    targetRevision: HEAD
    path: manifests/bentopdf
  destination:
    server: https://kubernetes.default.svc
    namespace: bentopdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true