---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semaphore
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://semaphoreui.github.io/charts
      chart: semaphore
      targetRevision: v1.17.1
      helm:
        releaseName: semaphore
        values: |
          crds:
            enabled: true
    - repoURL: git@github.com:storsteinbono/gitops.git
      targetRevision: HEAD
      path: apps/semaphore/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: semaphore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
  spec:
    admin:
      create: true
      password: [test123]
    database:
      type: postgres
      host: postgresql
      port: 5432
      usernameFromSecret: true
      usernameKey: username
      passwordKey: password
      existingSecret: semaphore-user 
